//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.example.application;

import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.TextView;
import com.example.application.R.layout;
import com.example.application.rest.RestClient_;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class SampleFragment_
    extends SampleFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        restClient = new RestClient_();
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        labelText = ((TextView) findViewById(com.example.application.R.id.label_text));
        {
            View view = findViewById(com.example.application.R.id.button1);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SampleFragment_.this.anotherButton();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_sample, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static SampleFragment_.FragmentBuilder_ builder() {
        return new SampleFragment_.FragmentBuilder_();
    }

    @Override
    public void anotherButton() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    SampleFragment_.super.anotherButton();
                } catch (RuntimeException e) {
                    Log.e("SampleFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public SampleFragment build() {
            SampleFragment_ fragment_ = new SampleFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
