//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.example.application.rest;

import java.util.HashMap;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.StringHttpMessageConverter;
import org.springframework.web.client.RestTemplate;

public class RestClient_
    implements RestClient
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public RestClient_() {
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new StringHttpMessageConverter());
        rootUrl = "http://pubsub.pubnub.com";
    }

    @Override
    public void sendMessage(String pubkey, String subkey, String signature, String channel, String callback, String message) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("pubkey", pubkey);
        urlVariables.put("subkey", subkey);
        urlVariables.put("signature", signature);
        urlVariables.put("channel", channel);
        urlVariables.put("callback", callback);
        urlVariables.put("message", message);
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        restTemplate.exchange(rootUrl.concat("/publish/{pubkey}/{subkey}/{signature}/{channel}/{callback}/{message}"), HttpMethod.GET, requestEntity, null, urlVariables).getBody();
    }

    @Override
    public void main() {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        restTemplate.exchange(rootUrl.concat("/"), HttpMethod.GET, requestEntity, null).getBody();
    }

}
